### PR TITLE
Try GitHub actions for 5.14

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
https://github.com/The-Compiler/pytest-xvfb/issues/22#issuecomment-636922245

**Comment by The-Compiler** [comment]
pytest-xvfb v2.0.0 is [released](https://github.com/The-Compiler/pytest-xvfb/releases/tag/v2.0.0) now - thanks for your patience, and let me know if any issues come up with the new release!

**Comment by altendky** [comment]
Kick CI

**Comment by altendky** [comment]
Kick CI again...

**Pull request merged**
